### ISSUE TITLE
figure out how to navigate filters in the gecko plot

### ISSUE THREAD

**Issue by elipapa** [opentargets/genetics#43] opened 2018-07-30 15:49 UTC
there are a large number of tissues and the checkbox + slider model is bound to break.

**Comment by andrewhercules** [comment] 2018-08-01 12:28
- [x] Develop low-fidelity mockups 
- [ ] Discuss filter/facet options and back-end integration with Miguel, Gareth, and Ed
- [ ] Share mockups with Genetics Core team for review/feedback
- [ ] Create high-fidelity prototype and pass to Gareth for implementation

**Comment by peatroot** [comment] 2018-09-19 13:37
Closing as duplicate of https://github.com/opentargets/genetics/issues/123

**Closed by peatroot** 2018-09-19 13:37 UTC
Labels: Kind: Question, Priority: Critical, Status: New
