### ISSUE TITLE
variant to disease table does not contain the proper number of studies

### ISSUE THREAD

**Issue by mkarmona** [opentargets/genetics#292] opened 2019-03-11 10:52 UTC
The total number of studies is `14027` although the number of studies included in the v2d should round 9k but definitely not hundreds as I currently have.

**Comment by edm1** [comment] 2019-03-11 11:44
The problem is occurring because `gs://genetics-portal-data/v2d/ld.parquet` contains old study IDs from V1 data.

I have updated this file to contain study IDs from V2 of the data.

However before we release, I will have to re-run the LD pipeline to produce LD data for all of our top loci (so that we have complete coverage).

**Comment by ElaineMcA** [comment] 2019-03-13 11:07
Will be fixed when pipeline re-run, cause addressed.

**Closed by ElaineMcA** 2019-03-13 11:07 UTC
Labels: Kind: Bug, Priority: High
